### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by neuromancer** [gurka/OpenCrystalCaves#1]
Hi,

It would be nice to have a README with instructions to compile and screenshots, so people can see the state of this re-implementation.

**Comment by gurka** [comment]
I wanted to wait until I've got everything ready and pushed so that anyone could clone this repo, build and play. But there are a few things missing right now, like the items/level data and all sprites. I don't want to upload the original sprites as they are but rather write something that could extract all sprites from the original game.

But until that is done I guess I could at least write a README that explains how to compile it, what libraries are needed and a few screenshots to show what it currently looks like.

**Comment by neuromancer** [comment]
> I wanted to wait until I've got everything ready and pushed so that anyone could clone this repo, build and play. But there are a few things missing right now, like the items/level data and all sprites. I don't want to upload the original sprites as they are but rather write something that could extract all sprites from the original game.

I agree.

> But until that is done I guess I could at least write a README that explains how to compile it, what libraries are needed and a few screenshots to show what it currently looks like.

That's great!

**Comment by gurka** [comment]
README and screenshots added in c3f81e4a50852583af68aab1de009e11985d4fdd! And I were able to create a sprite extractor as well, see 43bdd5a3dff1d4991be72f5745151347a0ab8180. The colors are currently a little bit off, but I'll work on that.
